# Generated by Django 6.0.4 on 2026-05-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('poster_url', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('watching', 'Watching'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.watchlist')),
            ],
        ),
    ]
